# Generated by Django 5.2.6 on 2025-09-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/icons/'),
        ),
    ]
