# Generated by Django 5.2.6 on 2025-09-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='media/icons/'),
        ),
    ]
