# Generated by Django 5.2.6 on 2025-09-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftsmanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='専門分野')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='経験年数')),
                ('workshop_location', models.CharField(blank=True, max_length=200, verbose_name='工房の所在地')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='自己紹介')),
                ('registered', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='craftsman_info', to='accounts.profile')),
            ],
        ),
    ]
